# Generated by Django 5.2.17 on 2026-09-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('detection_count', models.PositiveIntegerField(default=0)),
                ('recurrence_days', models.PositiveIntegerField(default=0, help_text='Distinct days with a detection inside the recurrence window')),
                ('night_fraction', models.FloatField(default=0.0)),
                ('frp_mean', models.FloatField(default=0.0)),
                ('frp_max', models.FloatField(default=0.0)),
                ('frp_cv', models.FloatField(default=0.0, help_text='Coefficient of variation of FRP: low means a stable source')),
                ('brightness_max', models.FloatField(default=0.0)),
                ('best_confidence', models.CharField(default='nominal', max_length=16)),
                ('dist_industrial_m', models.FloatField(blank=True, null=True)),
                ('industrial_group', models.CharField(choices=[('petro_chemical', 'Petrochemical / refinery'), ('power_generation', 'Power generation'), ('metals_heavy', 'Metals / heavy manufacturing'), ('light_manufacturing', 'Light manufacturing / warehouse'), ('waste_landfill', 'Waste / landfill'), ('extraction_kiln', 'Extraction / quarry / kiln'), ('none', 'No mapped feature nearby')], default='none', max_length=32)),
                ('industrial_name', models.CharField(blank=True, max_length=200)),
                ('land_context', models.CharField(choices=[('built_up', 'Built-up'), ('cropland', 'Cropland'), ('tree_cover', 'Tree cover'), ('grass_shrub', 'Grassland / shrubland'), ('bare', 'Bare / sparse vegetation'), ('water', 'Water'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('label', models.CharField(choices=[('industrial_fire', 'Industrial fire'), ('persistent_source', 'Persistent thermal source'), ('vegetation_fire', 'Vegetation fire'), ('uncertain', 'Other / uncertain')], db_index=True, default='uncertain', max_length=32)),
                ('label_confidence', models.CharField(default='low', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('matched_rule', models.CharField(blank=True, max_length=80)),
                ('in_validation_corridor', models.BooleanField(db_index=True, default=False)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recurrence_days', '-frp_max'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='hotspots_si_latitud_3c9ba3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('acq_date', models.DateField(db_index=True)),
                ('acq_time', models.CharField(help_text='UTC HHMM as reported by FIRMS', max_length=8)),
                ('bright_ti4', models.FloatField(blank=True, null=True)),
                ('bright_ti5', models.FloatField(blank=True, null=True)),
                ('frp', models.FloatField(default=0.0)),
                ('confidence', models.CharField(blank=True, max_length=16)),
                ('daynight', models.CharField(blank=True, max_length=1)),
                ('satellite', models.CharField(blank=True, max_length=16)),
                ('instrument', models.CharField(blank=True, max_length=16)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='hotspots.site')),
            ],
            options={
                'ordering': ['-acq_date', '-acq_time'],
                'constraints': [models.UniqueConstraint(fields=('latitude', 'longitude', 'acq_date', 'acq_time', 'satellite'), name='unique_detection')],
            },
        ),
    ]
