# Generated by Django 5.2.17 on 2026-09-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='event_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='has_ongoing_event',
            field=models.BooleanField(db_index=True, default=False, help_text='An episode here has not yet been closed by a quiet gap'),
        ),
        migrations.AddField(
            model_name='site',
            name='max_event_duration',
            field=models.PositiveIntegerField(default=0, help_text='Longest continuous burning episode at this site, in days'),
        ),
        migrations.AddField(
            model_name='site',
            name='mean_gap_days',
            field=models.FloatField(blank=True, help_text='Average quiet interval between episodes; null if only one', null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('duration_days', models.PositiveIntegerField(help_text='Calendar days from first to last detection, inclusive')),
                ('active_days', models.PositiveIntegerField(help_text='Distinct days inside the span that actually had a detection')),
                ('density', models.FloatField(help_text='active_days / duration_days; 1.0 means it burned on every day of the span')),
                ('detection_count', models.PositiveIntegerField(default=0)),
                ('frp_mean', models.FloatField(default=0.0)),
                ('frp_max', models.FloatField(default=0.0)),
                ('frp_cv', models.FloatField(default=0.0)),
                ('brightness_max', models.FloatField(default=0.0)),
                ('peak_date', models.DateField(blank=True, null=True)),
                ('night_fraction', models.FloatField(default=0.0)),
                ('gap_before_days', models.PositiveIntegerField(blank=True, help_text="Days from the previous episode's last detection to this one's first; null for the first episode at a site", null=True)),
                ('is_ongoing', models.BooleanField(default=False, help_text='Not yet closed by a quiet gap, so it may still be burning')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hotspots.site')),
            ],
            options={
                'ordering': ['site_id', 'start_date'],
                'indexes': [models.Index(fields=['site', 'start_date'], name='hotspots_ev_site_id_ff36f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'start_date'), name='unique_event_start')],
            },
        ),
    ]
