# Generated by Django 5.2.17 on 2026-09-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_site_event_count_site_has_ongoing_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='longest_episode_active_days',
            field=models.PositiveIntegerField(default=0, help_text="Days with a detection inside that longest episode. Paired with max_event_duration it gives the episode's density, which is what separates a sustained burn from two blips three weeks apart."),
        ),
    ]
