# Generated by Django 5.2.17 on 2026-09-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0003_site_longest_episode_active_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='best_confidence',
            field=models.CharField(default='nominal', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='label',
            field=models.CharField(choices=[('industrial_fire', 'Industrial fire'), ('persistent_source', 'Persistent thermal source'), ('vegetation_fire', 'Vegetation fire'), ('uncertain', 'Other / uncertain')], db_index=True, default='uncertain', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='label_confidence',
            field=models.CharField(default='low', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='matched_rule',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
