# Generated by Django 5.2.17 on 2026-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0004_event_best_confidence_event_evidence_event_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='landcover_frac_builtup',
            field=models.FloatField(default=0.0, help_text='Share of the ~375 m detection footprint that is built-up or bare. The majority class alone is a single 10 m reading and flips on which pixel the centroid landed in; the fraction describes the whole pixel.'),
        ),
    ]
