# Generated by Django 5.2.17 on 2026-09-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0005_site_landcover_frac_builtup'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='review_label',
            field=models.CharField(blank=True, choices=[('industrial_fire', 'Industrial fire'), ('persistent_source', 'Persistent thermal source'), ('vegetation_fire', 'Vegetation fire'), ('uncertain', 'Other / uncertain')], help_text="Reviewer's classification, independent of the rule output", max_length=32),
        ),
        migrations.AddField(
            model_name='site',
            name='review_note',
            field=models.TextField(blank=True, help_text='Why the reviewer decided this'),
        ),
        migrations.AddField(
            model_name='site',
            name='review_source',
            field=models.CharField(choices=[('unreviewed', 'Not reviewed'), ('assistant', 'AI pre-annotation - map evidence only, no imagery'), ('human', 'Human verified against imagery')], db_index=True, default='unreviewed', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
