# Generated by Django 5.2.17 on 2026-09-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0006_site_review_label_site_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='landcover_frac_built_only',
            field=models.FloatField(default=0.0, help_text='Share of the footprint that is the Built-up class specifically, excluding bare ground. An industrial fire needs structures; bare scrubland beside a mapped works is not evidence of any.'),
        ),
    ]
